### PR TITLE
Update to latest version of CACKey

### PR DESCRIPTION
**Pull request by rkeene**
Added a lot of functionality and updates since the initial release.

### CODE REVIEW

**Comment by jbjonesjr** [comment]
is there a reason that wherever CACKey is being developed can't be tired directly to this GitHub repository?

**Clarification:** 
You have a pretty active development process for this @rkeene it seems (and maybe this is actually sourced from yet another upstream location).  Since this is maintained somewhere, can we get that promoted so this can be removed from the Conservatory (even if it has to be forge)?

**Comment by risacher** [comment]
@jbjonesjr, I suspect from previous discussions with @rkeene that the work is being done on gov't contract, and the upstream repo is private.   It was originally developed for USACE, then DHS - and now I know not who.   

The upstream versions may not be under the same license.

**Comment by kfogel** [comment]
I was about to ask the same question as @jbjonesjr -- thanks for the response, @risacher.  If it's truly the case that there's effectively no publicly-visible versioned upstream, then this should stay in the Conservatory, and @rkeene's repository can be viewed, from our point of view, as a staging area from which updates to the Conversatory version are supplied.  However, if active development is actually happening on @rkeene's version (rather than that version just reflecting development happening somewhere else), then yes, the Conservatory copy should go away.  @rkeene, you're the ultimate expert on this question, so please feel free to weigh in.

**Comment by kfogel** [comment]
(And I forgot to mention: thanks for the pull request, @rkeene.  Whatever the ultimate fate of the Conservatory archival copy, keeping up-to-date while it exists is a Good Thing, and you made that much easier.)

**Comment by kfogel** [comment]
Ah, looks like CAC-key access is required for the forge.mil repository (which seems somehow appropriate, given the project in question).   See http://cackey.rkeene.org/fossil/index (and in particular the https://software.forge.mil/sf/frs/do/listReleases/projects.community_cac/frs.cackey link there).

**Comment by jbjonesjr** [comment]
@kfogel it seems that software forge is currently down (shocking! I say), but I **think** I remember when looking into it before, even that site says "this development is done on some contract somewhere, so code isn't maintained here."

**Comment by kfogel** [comment]
Thanks @jbjonesjr.  Sounds to me like having the Conservatory copy is worthwhile then -- at least until ${somewhere} goes open source and hosts their code in a public repository :-).

**Pull request merged**
